name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - requests
  - mlflow
  - scikit-learn=0.24.1
  - pip:
      - wandb
      - git+https://github.com/borja-sc/mlops-for-predicting-rental-prices#egg=wandb-utils&subdirectory=components
