channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=23.2.1
- pip:
  - mlflow==2.6.0
  - cloudpickle==2.2.1
  - configparser==5.3.0
  - importlib-metadata==6.8.0
  - numpy==1.25.2
  - pandas==2.1.0
  - psutil==5.9.5
  - scikit-learn==0.24.1
  - scipy==1.11.2
name: mlflow-env
