wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694182200.462469
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      - 24
      4: 3.11.5
      5: 0.15.10
      8:
      - 5
